name: Mac OS build

on:
  workflow_dispatch:
  push:
    branches:
      - master
      - fixes
      - develop
      - release/*
    tags:
      - 'v[0-9]+.*'
  pull_request:
    branches:
      - master
      - fixes
      - develop
      - release/*

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  mosquitto:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4

      - name: pin cmake to 3.x series
        uses: jwlawson/actions-setup-cmake@09fd9b0fb3b239b4b68d9256cd65adf8d6b91da0
        with:
          cmake-version: '3.31.6'

      - name: Install Homebrew dependencies
        run: |
          brew update
          brew install \
            argon2 \
            cjson \
            cmake \
            cunit \
            docbook-xsl \
            gcc \
            googletest \
            libedit \
            libmicrohttpd \
            make \
            openssl \
            uthash

      - name: Configure CMake
        run: |
          EDITLINE_PREFIX=$(brew --prefix libedit)
          cmake -B ${{github.workspace}}/build \
            -G Ninja \
            -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} \
            -DDOCUMENTATION=OFF \
            -DCMAKE_INCLUDE_PATH="-I$EDITLINE_PREFIX/include" \
            -DCMAKE_LIBRARY_PATH="-I$EDITLINE_PREFIX/lib" \
            -DCMAKE_C_FLAGS="-I$EDITLINE_PREFIX/include" \
            -DCMAKE_CXX_FLAGS="-I$EDITLINE_PREFIX/include" \
            -DCMAKE_EXE_LINKER_FLAGS="-L$EDITLINE_PREFIX/lib" \
            -DOPENSSL_ROOT_DIR=$(brew --prefix openssl@3)

      - name: Build
        run: |
          cmake --build ${{github.workspace}}/build \
            --config ${{env.BUILD_TYPE}}

      - name: Test
        working-directory: ${{github.workspace}}/build/
        run: ctest --output-on-failure --repeat until-pass:5
